---
- hosts: 172.31.93.93
  become: yes
  tasks:
  - name: crate a file
    file:
      path: /home/ubuntu/mytestfile
      state: touch

  - name: remove a file
    file:
      path: /home/ubuntu/mytestfile
      state: absent

  - name: create a folder
    file:
      path: /home/ubuntu/mytestfolder
      state: directory       