---
- hosts: 172.31.93.93
  become: yes
  tasks:
  - name: crate a file
    file:
      path: /home/ubuntu/mytestfile
      state: touch

  - name: create a folder
    file:
      path: /home/ubuntu/mytestfolder
      state: directory       

  - name: copy a file form master to slave
    copy:
      src: my2ndfile.txt
      dest: /home/ubuntu/mytestfolder