---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: I would like to install apache2 webserver on ubuntu node
    apt:
      name: apache2
      state: present
    when: ansible_os_family=="Debian"

  - name: I would like to start apache2 webserver on ubuntu node
    service:
      name: apache2
      state: started
    when: ansible_os_family=="Debian"
   
   
  - name: I want to install webserver on RedHat node
    yum:
      name: httpd
      state: present
    when: ansible_os_family=="RedHat"

  - name: I want to start webserver on RedHat node
    service:
      name: httpd
      state: started
    when: ansible_os_family=="RedHat"