---
- hosts: all
  become: yes
  tasks:
  - name: I would like to install webserver
    apt:
      name: apache2
      state: present

  - name: I would like to install tree software
    apt:
      name: tree
      state: present     

  - name: I would like to install wget
    apt:
      name: wget
      state: present      

